# Remote theme directory
remote_theme: analytics-link/analytics-link.github.io

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme

#-------------------------------
# General Site Settings
title: Bradley Warren
description: "Hi I'm Bradley, I'm a Finance professional passionate about using data to solve complex business problems. My core expertise lies in financial planning, analysis, and strategic support, where I help organisations make informed capital allocation and growth decisions. Outside of traditional finance work, I enjoy experimenting with machine learning and statistical techniques to tackle questions like customer lifetime value, revenue optimisation, and market trend analysis. This combination of financial rigor and analytical curiosity allows me to approach business challenges from multiple angles and deliver more comprehensive insights."
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

#-------------------------------
# About Section
subtitle: Data Science <span style="color:#f58506"> Portfolio </span>
location: "London, UK"
resume_url: /docs/resume.docx
avatar_image: /img/BW_Temp_Photo.jpg

#-------------------------------
# Contact links
linkedln: "https://www.linkedin.com/in/bradley-warren-28580725/" # Add your linkedln handle
github: "https://github.com/bradleywarren4"  # Add your github handle

paginate: 6
paginate_path: "/page/:num"

sass:
  sass_dir: _sass
  style: compressed # possible values: nested expanded compact compressed

defaults:
  - scope:
      type: posts
    values:
      layout: post
      read_time: true
      share: false


#-------------------------------
# Exclude from processing.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/


